name: Deploy Rendered Site

on:
  # FIXME: This should only trigger on merging to main.
  push:
    # Make sure not to trigger on push to gh-pages!
    branches: [ deploy-action ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - uses: actions/checkout@v2
    - run: mdbook build
    - uses: EndBug/add-and-commit@v9
      with:
        add: './docs'
        message: 'auto deploy'
        new_branch: gh-pages
        pathspec_error_handling: exitAtEnd
        push: true
