name: Deploy Rendered Site

on: "push"
#on:
#  push:
#    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - uses: actions/checkout@v2
    - run: mdbook build
    - run: ls -laF
