name: Deploy Rendered Site

on:
  push:
    # TODO: This temporary brnach dev value should be `main` prior to merge:
    branches: [ direct-git-impl ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - uses: actions/checkout@v2

    # Each deploy overwrites the contents of `gh-pages` branch from
    # `main`, but also introduces a merge structure so that the history of
    # `gh-pages` is tracked:
    - name: Overwrite gh-pages branch with main branch
      run: |
        set -x
        git config --global user.name 'autodeploy'
        git config --global user.email 'autodeploy'
        git fetch
        TMP='local-temp-branch'
        git checkout -b "$TMP" # Same tree state as main branch
        git log --graph --all
        git merge \
          --strategy ours \
          --commit \
          -m 'Auto-deploy: overwriting with `main` branch' \
          origin/gh-pages
        git checkout gh-pages
        git merge --ff-only "$TMP"
        git branch -d "$TMP"
    - run: mdbook build
    - name: Unignore docs
      run: sed -i 's|^docs/$||' .gitignore
    - name: Disable jekyll
      run: touch .nojekyll
    - name: Commit and Push render to gh-pages
      run: |
        git add --all
        git commit -m 'Auto-deploy: rendered output
        git push
