name: Deploy Rendered Site

on: "push"
#on:
#  push:
#    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - run: cargo --version
#    - uses: actions/checkout@v3
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
